# Use Ubuntu as the base image
FROM ubuntu:latest

# Install required packages
RUN apt-get update && \
    apt-get install -y vim git openssh-server maven openjdk-21-jdk openjdk-8-jdk

# Set the root password to 'root' (replace with a secure password in production)
RUN echo 'root:root' | chpasswd

# Allow root login via SSH with password
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Enable password authentication in SSH
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Expose SSH port
EXPOSE 22

# Restart SSH service
RUN service ssh restart

# Start the SSH server
CMD ["/usr/sbin/sshd", "-D"]
